[package]
name = "consensus-bft"
version = "0.0.1"
authors = ["Eason Gao <kaoimin@qq.com>", "Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"
license = "MIT"

[dependencies]
arraymap = "0.1.1"
bft-rs = { git = "https://github.com/KaoImin/bft-rs.git", rev = "0021f60437a8f6a84be384f5c746eddd5ddfa1b6" }
blake2b_simd = "0.4.1"
crossbeam = "0.7"
rustc-serialize = "0.3"
log = "0.4.3"
lru-cache = "0.1"
rlp = "0.3.0"

[features]
default = ["verify_req"]
verify_req = ["bft-rs/verify_req"]
